#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
# hey

source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

if [ ! -f $OPENSHIFT_DATA_DIR/sqlite3.db ]
then
    echo "Copying $OPENSHIFT_REPO_DIR/wsgi/openshift/sqlite3.db to $OPENSHIFT_DATA_DIR"
    cp "$OPENSHIFT_REPO_DIR"wsgi/openshift/sqlite3.db $OPENSHIFT_DATA_DIR
    python "$OPENSHIFT_REPO_DIR".openshift/action_hooks/secure_db.py | tee ${OPENSHIFT_DATA_DIR}/CREDENTIALS
else
    echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/openshift/manage.py syncdb --noinput'"
    python "$OPENSHIFT_REPO_DIR"wsgi/openshift/manage.py syncdb --noinput
fi

if [ ! -d $OPENSHIFT_DATA_DIR/media ];
then
    mkdir $OPENSHIFT_DATA_DIR/media
fi

if [ ! -d $OPENSHIFT_DATA_DIR/media/CACHE ];
then
    mkdir $OPENSHIFT_DATA_DIR/media/CACHE
fi

if [ ! -d $OPENSHIFT_DATA_DIR/media/ckeditor ];
then
    mkdir $OPENSHIFT_DATA_DIR/media/ckeditor
fi

if [ ! -d $OPENSHIFT_DATA_DIR/media/ckeditor/uploads ];
then
    mkdir $OPENSHIFT_DATA_DIR/media/ckeditor/uploads
fi

if [ ! -d $OPENSHIFT_DATA_DIR/media/uploads ];
then
    mkdir $OPENSHIFT_DATA_DIR/media/uploads
fi

if [ ! -d $OPENSHIFT_DATA_DIR/media/slides ];
then
    mkdir $OPENSHIFT_DATA_DIR/media/slides
fi

ln -sf $OPENSHIFT_DATA_DIR/media $OPENSHIFT_REPO_DIR/wsgi/openshift/

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/openshift/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/openshift/manage.py collectstatic --noinput
